import { useEffect, useState } from 'react';
import { api } from './api';
interface Report {pageviews:number;visitors:number;days:{day:string;views:number;visitors:number}[];pages:{path:string;views:number}[];referrers:{host:string;views:number}[];devices:{device:string;views:number}[]}
const date=(time:number)=>new Date(time+8*3600_000).toISOString().slice(0,10);
export function AnalyticsPanel() {
  const [days,setDays]=useState(30),[report,setReport]=useState<Report|null>(null),[message,setMessage]=useState('');
  useEffect(()=>{let alive=true;api<Report>(`/api/v1/admin/analytics?from=${date(Date.now()-(days-1)*86400_000)}&to=${date(Date.now())}`).then(value=>{if(alive){setReport(value);setMessage('');}}).catch(e=>alive&&setMessage((e as Error).message));return()=>{alive=false;};},[days]);
  const max=Math.max(1,...(report?.days.map(d=>d.views)??[]));
  return <><div className="admin-heading"><div><span className="eyebrow">VISITOR NOTEBOOK</span><h1>访客数据</h1><p>看看哪些内容被读到，哪些日子有人经过。</p></div><label>时间范围<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>最近 {n} 天</option>)}</select></label></div>{message&&<p role="alert" className="admin-notice">{message}</p>}{report&&<><div className="admin-overview-grid admin-metrics"><div><span className="pixel-num">{report.pageviews.toLocaleString()}</span><span>页面浏览量</span></div><div><span className="pixel-num">{report.visitors.toLocaleString()}</span><span>每日独立访客累计</span></div><div><span className="pixel-num">{(report.pageviews/days).toFixed(1)}</span><span>日均浏览量</span></div></div><section className="admin-settings-card"><h2>每日访问</h2><div className="admin-chart" role="img" aria-label={`最近${days}天，每日浏览量趋势`}>
  {report.days.map(day=><div key={day.day} className="admin-chart-column" title={`${day.day}：${day.views} 次浏览，${day.visitors} 位访客`}><span style={{height:`${Math.max(day.views?2:0,day.views/max*100)}%`}}/><small>{day.day.slice(5)}</small></div>)}</div><details><summary>查看每日明细</summary><table className="admin-table"><thead><tr><th>日期</th><th>浏览量</th><th>独立访客</th></tr></thead><tbody>{report.days.map(day=><tr key={day.day}><td>{day.day}</td><td>{day.views}</td><td>{day.visitors}</td></tr>)}</tbody></table></details></section><div className="admin-grid">{[{title:'热门页面',rows:report.pages.map(p=>({label:p.path,value:p.views}))},{title:'访问来源',rows:report.referrers.map(r=>({label:r.host,value:r.views}))},{title:'设备分布',rows:report.devices.map(d=>({label:{mobile:'手机',tablet:'平板',desktop:'桌面'}[d.device]??d.device,value:d.views}))}].map(group=><section className="admin-settings-card" key={group.title}><h2>{group.title}</h2>{group.rows.map(row=><div className="admin-stat-row" key={row.label}><span>{row.label}</span><strong>{row.value}</strong></div>)}{!group.rows.length&&<p className="muted">暂时还没有访问记录。</p>}</section>)}</div></>}
  <p className="muted admin-analytics-note">按台北时区统计，保留 90 天。仅记录页面路径、来源域名和设备类别；不保存 IP、完整来源链接或浏览器标识。访客标识每天更新，因此跨日累计会包含重复来访的人。站主、管理页、预览页及开启 DNT/GPC 的访问不计入。</p></>;
}
