import { useEffect, useState } from 'react';
import { RESOURCE_KINDS } from '../../contracts/content';
import { RESOURCE_LABELS } from '../../contracts/editor';
import { api } from './api';
interface Token {id:string;name:string;scopes:string[];expiresAt:string;revoked:boolean;lastUsedAt?:string|null}
export function SecurityPanel({onLogout}:{onLogout:()=>void}) {
  const [tokens,setTokens]=useState<Token[]>([]),[name,setName]=useState('本地 AI 发布'),[scopes,setScopes]=useState<string[]>(['essays:write','media:write']),[expires,setExpires]=useState(new Date(Date.now()+30*86400_000).toISOString().slice(0,10)),[issued,setIssued]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState('');
  const load=()=>api<Token[]>('/api/v1/auth/tokens').then(setTokens);
  useEffect(()=>{load().catch(e=>setMessage((e as Error).message));},[]);
  async function issue(){setBusy(true);setIssued('');try{const result=await api<{token:string}>('/api/v1/auth/tokens',{method:'POST',body:{name,scopes,expiresAt:new Date(`${expires}T23:59:59+08:00`).toISOString()}});setIssued(result.token);await load();setMessage('Token 已创建，请保存到本地环境变量；离开后不会再次显示原文。');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function revoke(id:string){try{await api(`/api/v1/auth/tokens/${encodeURIComponent(id)}`,{method:'DELETE'});await load();setMessage('Token 已撤销，立即失效。');}catch(e){setMessage((e as Error).message);}}
  async function password(){if(newPassword!==confirm){setMessage('两次新密码不一致。');return;}setBusy(true);try{await api('/api/v1/auth/password',{method:'PUT',body:{currentPassword,newPassword}});setCurrentPassword('');setNewPassword('');setConfirm('');onLogout();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <><div className="admin-heading"><div><span className="eyebrow">OWNER ACCESS</span><h1>Token 与账户</h1><p>网页通过你的会话管理内容；CLI 使用可限制范围和到期时间的 Token。</p></div></div>{message&&<p className="admin-notice" role="status">{message}</p>}<section className="admin-settings-card"><h2>创建 CLI Token</h2><div className="admin-grid"><label>Token 名称<input value={name} onChange={e=>setName(e.target.value)}/></label><label>到期日期<input type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></label></div><fieldset className="admin-scope-list"><legend>允许操作的内容</legend>{[...RESOURCE_KINDS,'media','analytics'].map(kind=><div key={kind}><strong>{kind==='media'?'文件上传':kind==='analytics'?'访客统计':RESOURCE_LABELS[kind as keyof typeof RESOURCE_LABELS]}</strong>{(kind==='analytics'?['read']:['read','write']).map(mode=>{const scope=`${kind}:${mode}`;return <label key={mode}><input type="checkbox" checked={scopes.includes(scope)} onChange={e=>setScopes(e.target.checked?[...scopes,scope]:scopes.filter(s=>s!==scope))}/>{mode==='read'?'读取':'编辑（含读取）'}</label>;})}</div>)}</fieldset><button className="btn btn-primary" disabled={busy||!scopes.length||!name.trim()} onClick={()=>void issue()}>创建 Token</button>{issued&&<label className="admin-token">仅显示这一次<textarea readOnly value={issued} rows={3}/></label>}</section>
  <section className="admin-settings-card"><h2>已创建 Token</h2>{tokens.map(token=><div key={token.id} className="admin-token-row"><div><strong>{token.name}</strong><p className="muted">到期：{token.expiresAt?.slice(0,10)} · {token.revoked?'已撤销':Date.parse(token.expiresAt)<=Date.now()?'已到期':'有效'}</p><small>{token.scopes.join(' · ')}</small></div><button className="btn" disabled={!!token.revoked} onClick={()=>void revoke(token.id)}>撤销</button></div>)}{!tokens.length&&<p className="muted">还没有 Token。</p>}</section>
  <section className="admin-settings-card"><h2>更改密码</h2><p className="muted">密码至少 12 个字符。更改后所有会话和 Token 会失效，需要重新登录。</p><form onSubmit={e=>{e.preventDefault();void password();}}><div className="admin-grid"><label>当前密码<input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required/></label><label>新密码<input type="password" autoComplete="new-password" minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></label><label>确认新密码<input type="password" autoComplete="new-password" minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label></div><button className="btn" disabled={busy} type="submit">更新密码并退出</button></form></section></>;
}

