/** Editable public control defaults; games and pixel artwork are deliberately excluded. */
export const INTERFACE_COPY_DEFAULTS: Record<string,string> = {
  "ui.abc44243": "切换到浅色",
  "ui.c3026897": "切换到深色",
  "ui.db76bc54": "首页",
  "ui.197c30db": "暂停",
  "ui.f51ff3f2": "播放",
  "ui.faf95013": "播放出错",
  "ui.4ec9cc57": "取消静音",
  "ui.60e54e25": "静音",
  "ui.3bab00da": "收起",
  "ui.8c7d7310": "展开",
  "ui.36a25416": "图片查看器",
  "ui.64af3d08": "这里",
  "ui.9318ccca": "离线示意图",
  "ui.e9b63b73": "继续轮转",
  "ui.d8220039": "暂停轮转",
  "ui.3b5d4715": "无法播放",
  "ui.5bd770d2": "上移",
  "ui.53d392a3": "下移",
  "ui.cbec2868": "主导航",
  "ui.a4fc40d8": "跳到正文",
  "ui.ac0bd104": "©",
  "ui.b20bda76": "·",
  "ui.af35a192": "分钟",
  "ui.26466f26": "图解",
  "ui.8c4d6b61": "这篇文章不存在或已被移动",
  "ui.55b67db7": "回到随笔列表",
  "ui.96756663": "面包屑",
  "ui.506ac0de": "随笔",
  "ui.a736fc61": "字 · 约",
  "ui.32e1ecb2": "文章没能加载出来",
  "ui.4e941a37": "重试",
  "ui.e1407260": "上一篇",
  "ui.aee2653b": "下一篇",
  "ui.cdecdd58": "搜索随笔",
  "ui.427e1526": "篇",
  "ui.f0550a3f": "没有找到相关文章",
  "ui.dedf90b9": "换个关键词，或者在左侧选择其它分类。",
  "ui.979b0c1f": "随笔目录",
  "ui.e96d8fd3": "文章目录",
  "ui.871f67c3": "Contents",
  "ui.44164427": "去过",
  "ui.bc7ccc4b": "个地方 ·",
  "ui.c9be24e0": "个省份 · 还想去",
  "ui.2f61a13d": "个",
  "ui.e23da036": "去过的地方",
  "ui.39b523bd": "关闭",
  "ui.56c6c8d4": "· 去过",
  "ui.9945555c": "足迹示意图",
  "ui.f21635f4": "重新加载高德地图",
  "ui.b25414f2": "下一次想去的地方",
  "ui.b8aee9a1": "图库还是空的",
  "ui.c56a4c97": "照片整理好后，会出现在这里。",
  "ui.2a0c975e": "/",
  "ui.b7f94d9e": "照片轮播",
  "ui.887a2545": "上一张",
  "ui.4977d91a": "放大查看",
  "ui.53a929fa": "下一张",
  "ui.cd66521d": "照片缩略图",
  "ui.f9ab3cf4": "个人资料尚未设置。",
  "ui.da0c196e": "_",
  "ui.1eafa50d": "：",
  "ui.7ade33e2": "打开播放列表",
  "ui.c88347f": "音乐播放器",
  "ui.1c6a23d2": "播放模式",
  "ui.314837e3": "上一首",
  "ui.dc7ee938": "下一首",
  "ui.7613cd35": "播放列表",
  "ui.3af264d7": "播放进度",
  "ui.3579e8b7": "音量",
  "ui.fbfb13f": "Mermaid 图渲染失败：",
  "ui.17e91164": "出了点小状况",
  "ui.bc93cdc5": "网站已更新，刷新页面",
  "ui.8e1ad9d1": "缩小",
  "ui.200c87a0": "%",
  "ui.dc0ca772": "放大",
  "ui.a0c3958f": "复位"
};
export const INTERFACE_ICON_DEFAULTS = {
  "nav.theme.sun": "sun",
  "nav.theme.moon": "moon",
  "music.pause": "pause",
  "music.play": "play",
  "music.expand": "down",
  "music.collapse": "up",
  "music.loop": "repeat",
  "music.one": "repeatOne",
  "music.shuffle": "shuffle",
  "music.mute": "mute",
  "music.volume": "volume",
  "wish.play": "play",
  "wish.pause": "pause",
  "folder.expand": "right",
  "folder.collapse": "down",
  "folder.root": "list",
  "folder.open": "folderOpen",
  "folder.closed": "folder",
  "profile.contact.email": "mail",
  "profile.contact.phone": "user",
  "profile.contact.link": "external",
  "profile.experience": "briefcase",
  "profile.projects": "flag",
  "profile.education": "school",
  "essayreader.right.0": "right",
  "essayreader.calendar.1": "calendar",
  "essayreader.clock.2": "clock",
  "essayspage.search.0": "search",
  "essayspage.folder.1": "folder",
  "footprintspage.pin.0": "pin",
  "footprintspage.close.1": "close",
  "footprintspage.flag.2": "flag",
  "gallerypage.left.0": "left",
  "gallerypage.zoomIn.1": "zoomIn",
  "gallerypage.right.2": "right",
  "gallerypage.pin.3": "pin",
  "gallerypage.calendar.4": "calendar",
  "profilesection.sparkle.0": "sparkle",
  "profilesection.download.1": "download",
  "profilesection.sparkle.2": "sparkle",
  "profilesection.award.3": "award",
  "profilesection.award.4": "award",
  "navplayer.prev.0": "prev",
  "navplayer.next.1": "next",
  "navplayer.up.2": "up",
  "navplayer.down.3": "down",
  "lightbox.zoomOut.0": "zoomOut",
  "lightbox.zoomIn.1": "zoomIn",
  "lightbox.reset.2": "reset",
  "lightbox.close.3": "close",
  "lightbox.left.4": "left",
  "lightbox.right.5": "right"
} as const;
export const INTERFACE_ICON_LABELS: Record<string,string> = {
  "nav.theme.sun": "nav.theme.sun",
  "nav.theme.moon": "nav.theme.moon",
  "music.pause": "music.pause",
  "music.play": "music.play",
  "music.expand": "music.expand",
  "music.collapse": "music.collapse",
  "music.loop": "music.loop",
  "music.one": "music.one",
  "music.shuffle": "music.shuffle",
  "music.mute": "music.mute",
  "music.volume": "music.volume",
  "wish.play": "wish.play",
  "wish.pause": "wish.pause",
  "folder.expand": "folder.expand",
  "folder.collapse": "folder.collapse",
  "folder.root": "folder.root",
  "folder.open": "folder.open",
  "folder.closed": "folder.closed",
  "profile.contact.email": "profile.contact.email",
  "profile.contact.phone": "profile.contact.phone",
  "profile.contact.link": "profile.contact.link",
  "profile.experience": "profile.experience",
  "profile.projects": "profile.projects",
  "profile.education": "profile.education",
  "essayreader.right.0": "EssayReader · right",
  "essayreader.calendar.1": "EssayReader · calendar",
  "essayreader.clock.2": "EssayReader · clock",
  "essayspage.search.0": "EssaysPage · search",
  "essayspage.folder.1": "EssaysPage · folder",
  "footprintspage.pin.0": "FootprintsPage · pin",
  "footprintspage.close.1": "FootprintsPage · close",
  "footprintspage.flag.2": "FootprintsPage · flag",
  "gallerypage.left.0": "GalleryPage · left",
  "gallerypage.zoomIn.1": "GalleryPage · zoomIn",
  "gallerypage.right.2": "GalleryPage · right",
  "gallerypage.pin.3": "GalleryPage · pin",
  "gallerypage.calendar.4": "GalleryPage · calendar",
  "profilesection.sparkle.0": "ProfileSection · sparkle",
  "profilesection.download.1": "ProfileSection · download",
  "profilesection.sparkle.2": "ProfileSection · sparkle",
  "profilesection.award.3": "ProfileSection · award",
  "profilesection.award.4": "ProfileSection · award",
  "navplayer.prev.0": "NavPlayer · prev",
  "navplayer.next.1": "NavPlayer · next",
  "navplayer.up.2": "NavPlayer · up",
  "navplayer.down.3": "NavPlayer · down",
  "lightbox.zoomOut.0": "Lightbox · zoomOut",
  "lightbox.zoomIn.1": "Lightbox · zoomIn",
  "lightbox.reset.2": "Lightbox · reset",
  "lightbox.close.3": "Lightbox · close",
  "lightbox.left.4": "Lightbox · left",
  "lightbox.right.5": "Lightbox · right"
};
export const ICON_NAMES = ["user","image","map","pen","music","sun","moon","left","right","down","up","close","play","pause","prev","next","shuffle","repeat","repeatOne","volume","mute","folder","folderOpen","file","search","pin","calendar","clock","mail","download","external","zoomIn","zoomOut","reset","gamepad","sparkle","list","video","heart","menu","flag","award","briefcase","school","code"] as const;
